version: '3.5'
services:
  server:
    # To use this compose file you need to first run `docker build -t r5reloaded-server -f Dockerfile`
    image: localhost/r5reloaded-server:latest
    ports:
      - 37000:37000/udp
    restart: 'unless-stopped'
    #volumes:
    #  - /path/to/custom/cfg/folder:/home/r5reloaded/server/platform/cfg:Z
    #  - /path/to/custom/playlists_r5_patch.txt:/home/r5reloaded/server/platform/playlists_r5_patch.txt:Z
    environment:
      # DONT ADD QUOTES AROUND THE ENVIRONMENT VARIABLES
      # Extra args to set when launching
      - ARGS=+sv_pylonVisibility 2 +map mp_rr_arena_composite
      # Server name
      - NAME=1v1 server
      # Playlist to use
      - PLAYLIST=fs_1v1
